<i18n locale="zh-CN" lang="yaml">
Emitter : 发送方
Event   : 事件
Receiver: 接收方
Data    : 数据
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Data: 數據
Emitter: 發送方
Event: 事件
Receiver: 接收方
</i18n>
<i18n locale="zh-TW" lang="yaml">
Data: 資料
Emitter: 傳送方
Event: 事件
Receiver: 接收方
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- Header area -->
      <el-header height="60px">
        <div class="common-page-header">
          <h1>WebSocket</h1>
          <div class="header-control">
            <el-select size="small" v-model="filterEvent" clearable :placeholder="$t('Filter Event')" class="event-filter">
              <el-option v-for="e in events"
                :label="e.label"
                :key="e.value"
                :value="e.value"></el-option>
            </el-select>

            <el-select size="small" v-model="filterConnector" clearable :placeholder="$t('Filter Connector')" class="connector-filter">
              <el-option v-for="c in connectors"
                :label="c.label"
                :key="c.value"
                :value="c.value"></el-option>
            </el-select>

            <el-input :placeholder="$t('Filter')"
              size="small"
              class="filter-input"
              v-model="filterInput"
              @input="onFilterChange">
              <i slot="prefix"
                class="el-input__icon el-icon-close text-main"
                v-if="filterInput"
                @click="filterInput = ''; onFilterChange()"></i>
            </el-input>
          </div>
        </div>
      </el-header>

      <!-- List area -->
      <el-main class="common-table-container">
        <el-table
          class="common-table" height="100%"
          size="mini"
          :default-sort="{ prop: 'timestampMs', order: 'descending'}"
          :data="filteredData">

          <el-table-column :label="$t('Seq')" width="100">
            <template slot-scope="scope">
              <span>{{ scope.row.seq }}</span>
            </template>
          </el-table-column>

          <el-table-column prop="timestampMs"
            sortable :sort-orders="['ascending', 'descending']"
            :label="$t('Time')" width="180">
            <template slot-scope="scope">
              <span>{{ scope.row.timestampMs | datetime }}</span>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Connector')" width="280">
            <template slot-scope="scope">
              <span class="text-info">ID</span>
              &nbsp;<code class="text-main">{{ scope.row.connectorId }}</code>

              <br>
              <span class="text-info">API Key ID</span>
              &nbsp;<code class="text-main">{{ scope.row.guanceAPIKeyId }}</code>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Emitter')" align="right" width="140">
            <template slot-scope="scope">
              <template v-if="scope.row.type === 'event'">
                <span class="event-from">{{ scope.row.from }}</span>
              </template>
              <template v-else>
                <span class="event-to">{{ scope.row.to }}</span>
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Event')" align="center" width="150">
            <template slot-scope="scope">
              <template v-if="scope.row.type === 'event'">
                <small>{{ scope.row.type }}</small>
                <i class="fa fa-fw fa-long-arrow-right"></i>
              </template>
              <template v-else>
                <i class="fa fa-fw fa-long-arrow-left"></i>
                <small>{{ scope.row.type }}</small>
              </template>
              <br><code :class="{ 'text-theme': scope.row.event.indexOf('.ack') < 0 }">{{ scope.row.event }}</code>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Receiver')" align="left" width="140">
            <template slot-scope="scope">
              <template v-if="scope.row.type === 'event'">
                <span class="event-to">{{ scope.row.to }}</span>
              </template>
              <template v-else>
                <span class="event-from">{{ scope.row.from }}</span>
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Data')">
            <template slot-scope="scope">
              <pre>{{ JSON.stringify(scope.row.data) }}</pre>
            </template>
          </el-table-column>

          <el-table-column align="right" width="150">
            <template slot-scope="scope">
              <el-link type="primary" @click="showDetail(scope.row)">{{ $t('Show detail') }}</el-link>
            </template>
          </el-table-column>
        </el-table>
      </el-main>

      <JSONViewerDialog ref="jsonViewerDialog" :showDownload="true" mode="json" />
    </el-container>
  </transition>
</template>

<script>
import { debounce } from '@/toolkit'
import JSONViewerDialog from '@/components/JSONViewerDialog'

export default {
  name: 'GuanceWebSocketDebugger',
  components: {
    JSONViewerDialog,
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
  },
  methods: {
    onFilterChange: debounce(function(val) {
      this.filterTEXT = val;
    }),
    async loadData() {
      let apiRes = await this.T.callAPI_get('/api/v1/debug/recent-websocket-messages/do/get');
      if (!apiRes || !apiRes.ok) return;

      let data = apiRes.data;

      let connectorMap = {};
      let eventMap     = {};
      data.forEach(d => {
        // Add search keyword
        this.common.appendSearchKeywords(d, [
          d.connectorId,
          d.guanceAPIKeyId,
          d.event,
          JSON.stringify(d.data),
        ]);

        // Get Event list
        let eventKey = d.event.replace(/\.ack$/, '');
        eventMap[eventKey] = {
          label: `${this.$t('Event')}: ${eventKey} / .ack`,
          value: eventKey,
        };

        // Get Connector list
        let connectorKey = `${d.connectorId}/${d.guanceAPIKeyId}`;
        connectorMap[connectorKey] = {
          label: `${this.$t('Connector')} ID: ${d.connectorId} / API Key ID: ${d.guanceAPIKeyId}`,
          value: connectorKey,
        };
      });

      this.data = data;
      this.connectors = Object.values(connectorMap);
      this.events     = Object.values(eventMap);

      this.$store.commit('updateLoadStatus', true);
    },
    showDetail(d) {
      let createTimeStr = this.M(d.timestampMs).format('YYYYMMDD_HHmmss');
      let fileName = `${d.event}-${d.from}-${d.to}.${createTimeStr}.json`;

      let message = this.T.jsonCopy(d);
      delete message.searchKeywords;

      this.$refs.jsonViewerDialog.update(message, fileName);
    },
  },
  computed: {
    filteredData() {
      let q = (this.filterTEXT || '').toLowerCase().trim();

      let data = this.data;

      // Filter by keyword
      if (q) {
        data = this.common.filterByKeywords(q, data);
      }

      // Filter by Event
      if (this.T.notNothing(this.filterEvent)) {
        data = data.filter(d => d.event === this.filterEvent || d.event === `${this.filterEvent}.ack`);
      }

      // Filter by Connector
      if (this.T.notNothing(this.filterConnector)) {
        let filterConnectorParts = this.filterConnector.split('/');
        data = data.filter(d => d.connectorId === filterConnectorParts[0] && d.guanceAPIKeyId === filterConnectorParts[1]);
      }

      return data;
    },
  },
  data() {
    return {
      data: [],
      events    : [],
      connectors: [],

      filterInput    : '',
      filterTEXT     : '',
      filterEvent    : {},
      filterConnector: {},
    }
  },
}
</script>

<style scoped>
.event-filter {
  width: 220px;
}
.connector-filter {
  width: 300px;
}
.filter-input {
  width: 260px;
  display: inline-block;
}
.filter-input input {
  font-size: 14px;
}
.filter-input .el-icon-close {
  cursor: pointer;
  font-weight: bold;
}

.event-from,
.event-to {
  text-transform: capitalize;
  font-size: 18px;
}
.event-from {
  color: var(--primary);
}
.event-to {
  color: var(--text-xlight);
}
pre {
  max-height: 60px;
  overflow: hidden;
  margin: 0;
}
</style>
<style>
</style>
