<i18n locale="zh-CN" lang="yaml">
Script Set not exists: 脚本集不存在
Script not exists    : 脚本不存在

Script ID: 脚本 ID
Original Script ID: 原脚本 ID
Publish Version: 发布版本

No Recent Script Publish History: 无近期脚本发布历史
All recent published Scripts will be collected by the system and shown here: 所有近期发布的脚本会被系统搜集并展示在此
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
All recent published Scripts will be collected by the system and shown here: 所有近期發佈的腳本會被系統蒐集並展示在此
No Recent Script Publish History: 無近期腳本發佈歷史
Original Script ID: 原腳本 ID
Publish Version: 發佈版本
Script ID: 腳本 ID
Script Set not exists: 腳本集不存在
Script not exists: 腳本不存在
</i18n>
<i18n locale="zh-TW" lang="yaml">
All recent published Scripts will be collected by the system and shown here: 所有近期釋出的指令碼會被系統蒐集並展示在此
No Recent Script Publish History: 無近期指令碼釋出歷史
Original Script ID: 原指令碼 ID
Publish Version: 釋出版本
Script ID: 指令碼 ID
Script Set not exists: 指令碼集不存在
Script not exists: 指令碼不存在
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <transition name="fade">
    <el-container direction="vertical" v-show="$store.state.isLoaded">
      <!-- Header area -->
      <el-header height="60px">
        <div class="common-page-header">
          <div>
            <h1>{{ $t('Script Publish History') }}</h1>
            <small class="text-info">
              &#12288;
              <span class="filter-item" v-if="dataFilter.scriptId">
                {{ $t('Script ID')}}
                <code class="text-main">{{ dataFilter.scriptId }}</code>
                <CopyButton :content="dataFilter.scriptId" />
              </span>
            </small>
          </div>

          <div class="header-control">
            <FuzzySearchInput :dataFilter="dataFilter"></FuzzySearchInput>
          </div>
        </div>
      </el-header>

      <!-- List area -->
      <el-main class="common-table-container">
        <div class="no-data-area" v-if="T.isNothing(data)">
          <h1 class="no-data-title" v-if="T.isPageFiltered()"><i class="fa fa-fw fa-search"></i>{{ $t('No matched data found') }}</h1>
          <h1 class="no-data-title" v-else><i class="fa fa-fw fa-info-circle"></i>{{ $t('No Recent Operation Records') }}</h1>

          <p class="no-data-tip">
            {{ $t('All recent published Scripts will be collected by the system and shown here') }}
          </p>
        </div>
        <el-table v-else
          class="common-table" height="100%"
          :data="data"
          :row-class-name="common.getHighlightRowCSS">

          <el-table-column :label="$t('Time')" width="200">
            <template slot-scope="scope">
              <span>{{ scope.row.createTime | datetime }}</span>
              <br>
              <span class="text-info">{{ scope.row.createTime | toNow }}</span>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Publish Version')" align="center" width="150">
            <template slot-scope="scope">
              <code class="text-main">{{ scope.row.scriptPublishVersion }}</code>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Script Set')">
            <template slot-scope="scope">
              <template v-if="scope.row.sset_id">
                <strong>{{ scope.row.sset_title || scope.row.sset_id }}</strong>
                <br>

                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.sset_id }}</code>
                <CopyButton :content="scope.row.sset_id" />
              </template>
              <template v-else>
                <strong class="text-bad">{{ $t('Script Set not exists') }}</strong>
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Script')">
            <template slot-scope="scope">
              <template v-if="scope.row.scpt_id">
                <strong>{{ scope.row.scpt_title || scope.row.scpt_id }}</strong>
                <br>

                <span class="text-info">ID</span>
                &nbsp;<code class="text-main">{{ scope.row.scpt_id }}</code>
                <CopyButton :content="scope.row.scpt_id" />
              </template>
              <template v-else>
                <strong class="text-bad">{{ $t('Script not exists') }}</strong>
              </template>
            </template>
          </el-table-column>

          <el-table-column :label="$t('Original Script ID')">
            <template slot-scope="scope">
              <code class="text-main">{{ scope.row.scriptId }}</code>
              <CopyButton :content="scope.row.scriptId" />
            </template>
          </el-table-column>

          <el-table-column align="right" width="150">
            <template slot-scope="scope">
              <el-link type="primary" @click="showScriptCode_cache(scope.row)">{{ $t('Show code') }}</el-link>
            </template>
          </el-table-column>
        </el-table>
      </el-main>

      <!-- Paging area -->
      <Pager :pageInfo="pageInfo" />

      <LongTextDialog :showDownload="true" mode="python" ref="longTextDialog" />
    </el-container>
  </transition>
</template>

<script>
import TimeDuration from '@/components/TimeDuration'
import LongTextDialog from '@/components/LongTextDialog'

export default {
  name: 'ScriptPublishHistoryList',
  components: {
    TimeDuration,
    LongTextDialog,
  },
  watch: {
    $route: {
      immediate: true,
      async handler(to, from) {
        await this.loadData();
      }
    },
  },
  methods: {
    async loadData() {
      let _listQuery = this.dataFilter = this.T.createListQuery();

      let apiRes = await this.T.callAPI_get('/api/v1/script-publish-history/do/list', {
        query: _listQuery,
      });
      if (!apiRes || !apiRes.ok) return;

      this.data = apiRes.data;
      this.pageInfo = apiRes.pageInfo;
      this.$store.commit('updateLoadStatus', true);
    },
    async showScriptCode_cache(d) {
      this.$store.commit('updateHighlightedTableDataId', d.id);

      let apiRes = await this.T.callAPI_getOne('/api/v1/script-publish-history/do/list', d.id, {
        query: { _withScriptCode_cache: true },
      });
      if (!apiRes || !apiRes.ok) return;

      let fileName = `${d.scriptId}.ver${d.scriptPublishVersion}.py`;
      this.$refs.longTextDialog.update(apiRes.data.scriptCode_cache, fileName);
    },
  },
  computed: {
  },
  props: {
  },
  data() {
    let _pageInfo   = this.T.createPageInfo();
    let _dataFilter = this.T.createListQuery();

    return {
      data    : [],
      pageInfo: _pageInfo,

      dataFilter: {
        _fuzzySearch: _dataFilter._fuzzySearch,
      },
    }
  },
}
</script>

<style scoped>
.filter-item + .filter-item:before {
  content: "|";
  position: relative;
  left: -6px;
}
.filter-item + .filter-item {
  margin-left: 10px;
}
</style>

<style>

</style>
