<i18n locale="zh-CN" lang="yaml">
Download as a JSON file: 作为 JSON 文件下载
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Download as a JSON file: 作為 JSON 文件下載
</i18n>
<i18n locale="zh-TW" lang="yaml">
Download as a JSON file: 作為 JSON 檔案下載
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <el-dialog
    id="JSONViewerDialog"
    :visible.sync="show"
    :close-on-click-modal="false"
    custom-class="long-text-dialog">
    <template slot="title">
      {{ title }}
      <span class="press-esc-to-close-tip">{{ $t('Press ESC to close') }}</span>
    </template>
    <div>
      <div class="download-link" v-if="showDownload && content">
        <el-link type="primary" @click="download">
          {{ $t('Download as a JSON file') }}
          <i class="fa fa-fw fa-download"></i>
        </el-link>
      </div>
      <json-viewer :value="jsonContent" theme="json-view-theme" show-double-quotes :show-array-index="false"></json-viewer>
    </div>
  </el-dialog>
</template>

<script>
import FileSaver from 'file-saver';

export default {
  name: 'JSONViewerDialog',
  components: {
  },
  watch: {
  },
  methods: {
    update(content, fileName) {
      this.content  = content;
      this.fileName = fileName;

      this.show = true;
    },
    download() {
      let blob = new Blob([this.content], {type: 'text/plain'});
      let fileName = this.fileName || `file-${this.M().format('YYYYMMDD_HHmmss')}.json`;
      FileSaver.saveAs(blob, fileName);
    },
  },
  computed: {
    jsonContent() {
      if ('string' === typeof this.content) {
        return JSON.parse(this.content);
      } else {
        return this.content;
      }
    }
  },
  props: {
    title       : String,
    showDownload: Boolean,
  },
  data() {
    return {
      show: false,

      fileName: null,
      content : null,
    }
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.download-link {
  margin-bottom: 15px;
}
</style>
<style>
.json-view-theme {
  font-size: 16px;
  border: 1px solid var(--border);
  border-radius: 5px;
  background-color: var(--base-light);
}

.json-view-theme .jv-code {
  padding: 5px;
}

.json-view-theme .jv-toggle {
  position: absolute;
  left: -15px;
  top: 5px;
}

.json-view-theme .jv-node .jv-node,
.json-view-theme .jv-node.toggle {
  margin-left: 25px !important;
}

.json-view-theme .jv-ellipsis {
  color: white;
  background-color: var(--primary);
  display: inline-block;
  line-height: 0.8;
  font-size: 16px;
  padding: 0px 8px 5px 8px;
  margin: 0 4px 0 4px;
  border-radius: 3px;
  vertical-align: 2px;
  cursor: pointer;
  user-select: none;
}

.json-view-theme .jv-link {
  font-family: "Iosevka";
  color: var(--primary);
}
.json-view-theme .jv-key {
  font-family: "Iosevka";
  margin-right: 10px;
}
.json-view-theme .jv-item {
  font-family: "Iosevka";
}
.json-view-theme .jv-item.jv-boolean { color: var(--warning) }
.json-view-theme .jv-item.jv-function { color: var(--success) }
.json-view-theme .jv-item.jv-number { color: var(--danger) }
.json-view-theme .jv-item.jv-number-float { color: var(--danger) }
.json-view-theme .jv-item.jv-number-integer { color: var(--danger) }
.json-view-theme .jv-item.jv-undefined { color: var(--warning) }
.json-view-theme .jv-item.jv-string {
  color: var(--success);
  word-break: break-word;
  white-space: normal;
}
</style>
