<i18n locale="zh-CN" lang="yaml">
Download as file: 作为文件下载
</i18n>

<!-- Generated by OpenCC START -->
<i18n locale="zh-HK" lang="yaml">
Download as file: 作為文件下載
</i18n>
<i18n locale="zh-TW" lang="yaml">
Download as file: 作為檔案下載
</i18n>
<!-- Generated by OpenCC END -->

<template>
  <el-dialog
    id="LongTextDialog"
    :visible.sync="show"
    :close-on-click-modal="false"
    custom-class="long-text-dialog">
    <template slot="title">
      {{ title }}
      <span class="press-esc-to-close-tip">{{ $t('Press ESC to close') }}</span>
    </template>
    <div>
      <div class="download-link" v-if="showDownload && content">
        <el-link type="primary" @click="download">
          {{ $t('Download as file') }}
          <i class="fa fa-fw fa-download"></i>
        </el-link>
      </div>
      <textarea id="longTextDialogContent"></textarea>
    </div>
  </el-dialog>
</template>

<script>
import FileSaver from 'file-saver';

export default {
  name: 'LongTextDialog',
  components: {
  },
  watch: {
  },
  methods: {
    update(content, fileName) {
      if (this.codeMirror) {
        // Clear previous content
        this.codeMirror.setValue('');
      }

      this.content  = content;
      this.fileName = fileName;

      this.show = true;

      setImmediate(() => {
        // Init editor
        if (!this.codeMirror) {
          let opt = { mode: this.mode || 'text' };
          this.codeMirror = this.T.initCodeMirror('longTextDialogContent', opt);
          this.codeMirror.setOption('theme', this.T.getCodeMirrorThemeName());
          this.T.setCodeMirrorReadOnly(this.codeMirror, true);
        }

        // Load code
        this.codeMirror.setValue(this.content || '');
        this.codeMirror.refresh();

        this.codeMirror.focus();
      });
    },
    download() {
      let blob = new Blob([this.content], {type: 'text/plain'});
      let fileName = this.fileName || `file-${this.M().format('YYYYMMDD_HHmmss')}.txt`;
      FileSaver.saveAs(blob, fileName);
    },
  },
  computed: {
  },
  props: {
    title       : String,
    mode        : String,
    showDownload: Boolean,
  },
  data() {
    return {
      show: false,

      fileName: null,
      content : null,

      codeMirror: null,
    }
  },
  beforeDestroy() {
    this.T.destoryCodeMirror(this.codeMirror);
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.download-link {
  margin-bottom: 15px;
}
</style>
<style>
#LongTextDialog .CodeMirror {
  height: 100%;
}
</style>
