# Generated by OpenCC

# 基礎演示
#
# 使用裝飾器為函數命名為 '兩數相加'，並允許外部調用本函數
# 額外的配置包括：
#   category='math'
#       指定分類為 "math"
#
#   tags=['basic', 'simple']
#       指定 2 個標籤：'basic', 'simple'
#
#   cache_result=300
#       指定處理結果緩存 300 秒。
#       首次調用成功後，後續使用完全相同的參數進行 API 調用時，系統將直接返回結果而不需要重新運行
#
#   timeout=10
#       指定函數執行超時時間為 10 秒
#       當函數執行超過 10 秒時，將強制中斷並退出
#
# (更多額外配置請參考腳本開發手冊 https://func.guance.com/doc/development-guide-builtin-features-dff-api/)

@DFF.API('兩數相加', category='math', tags=['math', 'simple'], cache_result=300, timeout=10)
def plus(x, y):
    '''
    兩數相加

    輸入參數 x, y 均為數字類型，返回結果為兩者之和
    '''
    print('INPUT: x = {}, y = {}'.format(x, y))

    _x = float(x)
    _y = float(y)
    result = _x + _y
    if isinstance(x, int) and isinstance(y, int):
        result = int(result)

    print('\tRESULT: {}'.format(result))
    return result

# 測試函數不需要裝飾器
def test_plus():
    assert plus(1, 1) == 2
    assert plus(1, 1.1) == 2.1
    assert plus(1.1, 1.2) == 2.3
    return 'OK'
